spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/navin5556/Ecommerce-project-configuration
          clone-on-start: true
server:
  port: 8085

