spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/navin5556/Ecommerce-project-configuration
          clone-on-start: true

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: Prod
#server:
#  port: 8085
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true
