spring:
  application:
    name: RatingService
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: microservices

server:
  port: 8089

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true